# Generated by Django 4.2.7 on 2023-11-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tarefa', models.CharField(max_length=100)),
                ('Descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('Data_tarefa', models.DateTimeField()),
                ('data_criacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Tarefas_agendadas',
            },
        ),
    ]
